site_name: Home User Guides
repo_url: https://github.com/sreeramachandramurthy/home-user-guides

nav:
  - 'Home': 'index.md'
  - 'Operating System':
    - 'Index': 'os/index.md'
    - 'Cent OS':
      - 'How To':
        - 'Change Hostname': 'os/centos/how-to/change-hostname.md'
        - 'Disable Sleep': 'os/centos/how-to/disable-sleep.md'
        - 'SSH Banner': 'os/centos/how-to/ssh-banner.md'
        - 'Static IP': 'os/centos/how-to/static-ip.md'
        - 'Temperature Sensors': 'os/centos/how-to/temperature-sensors.md'
      - 'Installation':
        - 'Install Docker Compose': 'os/centos/installation/install-docker-compose.md'
        - 'Install Docker': 'os/centos/installation/install-docker.md'
        - 'Install Java': 'os/centos/installation/install-java.md'
        - 'Install MongoDB': 'os/centos/installation/install-mongodb.md'
        - 'Install Python': 'os/centos/installation/install-python.md'
        - 'Install Robo 3T': 'os/centos/installation/install-robo3t.md'
        - 'Install VS Code': 'os/centos/installation/install-vscode.md'
    - 'Ubuntu':
      - 'Softwares': 'os/ubuntu/softwares.md'
      - 'How To':
        - 'Mount Drive on Boot': 'os/ubuntu/how-to/mount-drive-on-boot/mount-drive-on-boot.md'
        - 'Remove Snap': 'os/ubuntu/how-to/remove-snap/remove-snap.md'
      - 'Installation':
        - 'Install Arduino IDE': 'os/ubuntu/installation/install-arduino-ide.md'
        - 'Install Discord': 'os/ubuntu/installation/install-discord.md'
        - 'Install Docker CE': 'os/ubuntu/installation/install-docker.md'
        - 'Install FreeCAD': 'os/ubuntu/installation/install-freecad.md'
        - 'Install GIT': 'os/ubuntu/installation/install-git.md'
        - 'Install GIMP': 'os/ubuntu/installation/install-gimp.md'
        - 'Install Glances': 'os/ubuntu/installation/install-glances.md'
        - 'Install GNOME Shell Extensions': 'os/ubuntu/installation/install-gnome-shell-extensions.md'
        - 'Install InfluxDB': 'os/ubuntu/installation/install-influxdb.md'
        - 'Install Java': 'os/ubuntu/installation/install-java.md'
        - 'Install Kodi': 'os/ubuntu/installation/install-kodi.md'
        - 'Install MkDocs': 'os/ubuntu/installation/install-mkdocs.md'
        - 'Install Mosquitto': 'os/ubuntu/installation/install-mosquitto.md'
        - 'Install MySQL Workbench': 'os/ubuntu/installation/install-mysql-workbench.md'
        - 'Install MySQL': 'os/ubuntu/installation/install-mysql.md'
        - 'Install Net Tools': 'os/ubuntu/installation/install-net-tools.md'
        - 'Install Node & NPM': 'os/ubuntu/installation/install-node-npm.md'
        - 'Install OpenSSH': 'os/ubuntu/installation/install-openssh.md'
        - 'Install PuddleTAG': 'os/ubuntu/installation/install-puddletag.md'
        - 'Install Python': 'os/ubuntu/installation/install-python.md'
        - 'Install SNMP': 'os/ubuntu/installation/install-snmp.md'
        - 'Install Telegram': 'os/ubuntu/installation/install-telegram.md'
        - 'Install Ubuntu Server': 'os/ubuntu/installation/install-ubuntu-server.md'
        - 'Install VLC': 'os/ubuntu/installation/install-vlc.md'
        - 'Install VS Code': 'os/ubuntu/installation/install-vscode.md'
  - 'Tools':
    - 'Index': 'tools/index.md'
    - 'GIMP':
      - 'Passport Photos': 'tools/gimp/passport-photos.md'

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables

theme:
  name: material
  features:
    # - navigation.expand
    - content.code.copy
    - navigation.tabs
    - navigation.path
  palette:
    # Palette toggle for Automatic Mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to Light Mode
    # Palette toggle for Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    # Palette toggle for Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to System preference
